### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by richvreeland** [OmniSharp/omnisharp-sublime#135]
Running OmniSharp on a Mac. It appears to have stopped working, since one of the last updates (3083 or 3080) to Sublime Text. Nothing else has changed, and it was working great before ... can you derive any ideas from this output? Any help would be greatly appreciated, thanks.

```
response: "/Users/r/Git/metro/project/project-csharp.sln"
request: http://localhost:50570/autocomplete
======== request params ======== 
 b'{"filename": "/Users/r/Git/metro/project/Assets/Resources/Scripts/Audio/Playback/OneOffLinkCount.cs", "WantMethodHeader": true, "wordToComplete": "isD", "line": "24", "column": "6", "WantSnippet": true, "WantReturnType": true, "buffer": "using System;\\n\\n/* \\tThis sound is fired once. All additional events\\n\\ttriggered on the same pulse are disgarded. */\\n\\npublic class OneOffLinkCount : Playback {\\n\\n\\tpublic OneOffLinkCount(AudioEventFilter filter, string[] samples, float gain = 1f, int step = -1) : base(filter, samples) {\\n\\n\\t\\tthis.step = step;\\n\\t\\tthis.gain = gain;\\n\\t}\\n\\n\\tprotected override void OnPulse() {\\n\\n\\t\\tif (!GetEvents(1)) return;\\n\\t\\tPlayOneOff();\\n\\t}\\n\\n\\tprivate void PlayOneOff() {\\n\\n\\t\\tvar isDesiredStep = pulse.StepIndex == step || step == -1;\\n\\n\\t\\tisD\\n\\n\\t\\tif (isDesiredStep) {\\n\\n\\t\\t\\tvar i = audioEvents[0].Line.LiveLinkCount % samples.Length;\\n\\n\\t\\t\\tmodule.PlaySample(\\"mallet_\\" + samples[i], audioEvents[0].Pan, time, gain);\\n\\n\\t\\t\\taudioEvents.Clear();\\n\\t\\t}\\n\\t}\\n}"}'
Traceback (most recent call last):
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 334, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 38, in run
    response = http.urlopen('POST', url, body=data)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50570): Max retries exceeded with url: /autocomplete (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
```

**Comment by jchannon** [comment]
If you have the latest package installed v1.8.1 there was something in the
release notes that said you need to chmod a launcher file

chmod +x /Users/***ENTER YOUR USERNAME***/Library/Application\
Support/Sublime\ Text\
3/Packages/OmniSharp/PrebuiltOmniSharpServer/omnisharp

I will try and do that automatically on releases from now on...somehow ;)

**Comment by richvreeland** [comment]
A-ha! Thank you sir (:

**Comment by jchannon** [comment]
No worries :)

**Comment by luispedrofonseca** [comment]
This got me as well and the chmod fixed it. Thanks!

**Comment by nosami** [comment]
You should just make the launcher executable in the repo.

**Comment by jchannon** [comment]
How? Its executable on my local machine so assume that doesnt translate
when pushed

**Comment by nosami** [comment]
I could google that for you, or you could google it yourself.. .but
permissions should be persisted in the repo.

**Comment by jchannon** [comment]
google says git update-index --chmod=+x <file>

interesting....

**Comment by jchannon** [comment]
@nosami that seems to work. i assume any file changes will still keep those permissions :worried:

**Comment by tMaxx** [comment]
just to let you know, fresh install on Linux and this still seems to be the issue.

**Comment by jchannon** [comment]
even after a manual chmod +x

**Comment by tMaxx** [comment]
after manually chmod-ing it kinda works, but only to the point of launching omnisharp script, which in turn crashes because it can't find `omnisharp.exe` assembly (notice the lowercase name).

**Comment by jchannon** [comment]
Ah good spot! Fancy doing a PR?

**Comment by tMaxx** [comment]
done: #143

**Comment by jchannon** [comment]
merged! :smile:

**Comment by jchannon** [comment]
Can people try out the beta release 1.9.0-bet to spot any potential issues

**Comment by amaeland** [comment]
I still get this issue even after trying to chmod, ill try the beta now and see how that works.

**Comment by jchannon** [comment]
Beta doesn't work either. I'm still working on getting a decent beta out :(

**Comment by sksea** [comment]
Also running omnisharp-sublime on a mac. Sometimes works, but when it doesn't, console logs this. Any idea? I'm guessing mono server isn't running?
```
project file %s found /Users/andy/Desktop/chem/chem.sublime-project
solution path: /Users/andy/Desktop/chem/chem-csharp.sln
file changed
======== request ======== 
 Url: http://localhost:62484/codecheck 
 Data: {"column": "3", "line": "1", "filename": "/Users/andy/Desktop/chem/test.cs", "buffer": "us"}
Exception in thread Thread-129:
Traceback (most recent call last):
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 39, in run
    response = pool.urlopen('POST', self.url, body=self.data, timeout=self.timeout).data
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/andy/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62484): Max retries exceeded with url: /codecheck (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
```

**Comment by sksea** [comment]
also noticed each time I restart sublime, omnisharp auto-completion works for the first character typed, but then breaks again. Sounds vague, but I can elaborate.

**Comment by amaeland** [comment]
I get similar results as sksea, latest beta version didnt fix this issue for me neither.

**Comment by sksea** [comment]
Seems to be resolved by version 1.9.1.
I had to remove and reinstall through package manager (directly updating didn't work).
I noticed that it takes a bit of time for the omnisharp-sublime to load, even after sublime text is opened. This is probably naive, but I look for the mono-sgen activity to start in OSX's activity monitor. Apparently mono-sgen is just a garbage collector; a better approach might be to check if omnisharp-server, but I don't know how or if it's even a good idea.

**Comment by nosami** [comment]
Confirmed that the 1.9.1 fix works for @sksea on JabbR. We need the status indicator #139 doing to show Dead, Loading or Loaded statuses as sometime people think it's not working before the solution has finished loading.

**Comment by jchannon** [comment]
Agreed

**Comment by snebjornen** [comment]
Hi, I still get a similiar error in 1.9.1, even after chmod

```
======== request ======== 
 Url: http://localhost:50931/codecheck 
 Data: {"filename": "/Users/Morten/Documents/Unity/Feels5/Assets/ListenerPositioner.cs", "line": "20", "column": "1", "buffer": "using UnityEngine;\nusing System.Collections;\n\npublic class ListenerPositioner : MonoBehaviour {\n\n\n\tpublic float PositionSmooth = 8;\n\tpublic float RotationSmooth =1.7f;\n\n\n\tvoid OnEnable()\n\t{\n\t\ttransform.parent = null;\n\t\ttransform.position = GameController.Player.transform.position;\n\t\ttransform.eulerAngles = GameController.Camelot.Camera.transform.eulerAngles;\n\t\t//smoothedRot = transform.eulerAngles;\n\t\tsmoothedPos = transform.position;\n\n\t\tStartCoroutine(UpdateStuff());\n\n\t}\n\n\n\tVector3 smoothedPos = new Vector3();\n\t//Vector3 smoothedRot = new Vector3();\n\tIEnumerator UpdateStuff()\n\t{\n\t\twhile (true)\n\t\t{\n\t\t\tvar playerPos = GameController.Player.transform.position;\n\n\t\t\tsmoothedPos = iTween.Vector3Update(smoothedPos,playerPos,PositionSmooth);\n\t\t\ttransform.position = smoothedPos;\n\n\t\t\t//var camRot = GameController.Camelot.Camera.transform.forward;\n\n\t\t\ttransform.gameObject.RotateUpdate(GameController.Camelot.Camera.transform.eulerAngles,RotationSmooth);\n\n\n\t\t\tyield return null;\n\t\t}\n\t}\n\n\t// Update is called once per frame\n\tvoid Update () {\n\n\t}\n}\n"}
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 39, in run
    response = pool.urlopen('POST', self.url, body=self.data, timeout=self.timeout).data
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50931): Max retries exceeded with url: /codecheck (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
```

**Comment by sksea** [comment]
See if this helps:
- Remove mono using script on the bottom http://www.mono-project.com/docs/about-mono/supported-platforms/osx/
- Install mono through brew (worked better for me since v1.9.1)

**Comment by jchannon** [comment]
I don't think how mono is installed effects things. Sometimes it's when the
solution is not loaded I believe it kills omnisharp server. We need an
indicator to tell users that the solution is loaded. PRs welcome! :)

**Comment by sksea** [comment]
@jchannon wasn't there a sublime command for omnisharp to show server output? Don't see it anymore.  But maybe that could be used to determine if the solution completed loading.

**Comment by jchannon** [comment]
Right click - omnisharp - show server output

We would have to start omnisharp server via a sub process and append stdin
to a new panel. At the moment we shell out and that uses the built in
she'll panel. We would need to monitor the stdin to check that the solution
is loaded and alert the user and also append to a new panel so we can see
the server messages.

**Comment by bdjones** [comment]
Hi there :)

I'm seeing exactly the same Connection Refused error. Reinstalling mono worked on one of my machines, but not on the other. Is there anything else I can try to get around it? I'm using the latest version of the plugin off of Package Control on OS X 10.10.3.

**Comment by snebjornen** [comment]
I tried reinstalling everything (kvm, mono, omnisharp), but am still getting errors.
```
solution path: /Users/Morten/Documents/Unity/Feels5.1/Feels5.1.sln
file changed
======== request ======== 
 Url: http://localhost:50301/addtoproject 
 Data: {"buffer": "using System.Collections.Generic;\nusing System.IO;\nusing System.Linq;\nusing System.Text;\nusing SimpleJSON;\nusing UnityEngine;\n\nnamespace Assets.Scripts\n{\n#if UNITY_EDITOR\n    public class CamelotSettingParser : ScriptableObject\n    {\n        public static readonly string CamelotSettingFilePath = Application.dataPath + @\"\\CamelotSettings\\\";\n        public static readonly string StandardFullPath = CamelotSettingFilePath + \"Standard.txt\";\n\n        private string _folderName;\n        private string _fileName;\n        private static readonly List<CamelotSetting> _loadedSettings = new List<CamelotSetting>();\n\n        public string FolderName\n        {\n            get { return _folderName; }\n        }\n\n        public string FileName\n        {\n            get { return _fileName; }\n        }\n\n        public CamelotSettingParser(string folderName, string fileName)\n        {\n            GameObject parent = GameObject.Find(\"Camelot Settings\");\n            if (!parent)\n                parent = new GameObject(\"Camelot Settings\");\n            var children = parent.GetComponentsInChildren<CamelotSetting>();\n\n            GameObject go;\n            var preLoadedChild = children.FirstOrDefault(c => c.Title == fileName);\n            if (preLoadedChild != null)\n                go = preLoadedChild.gameObject;\n            else\n            {\n                go = new GameObject(fileName);\n                go.transform.parent = parent.transform;\n            }\n\n            _folderName = folderName;\n            _fileName = fileName;\n\n            var path = Application.dataPath + @\"\\\" + folderName;\n            if (!Directory.Exists(path))\n            {\n                Directory.CreateDirectory(path);\n            }\n            if (!File.Exists(path + fileName))\n            {\n                var f = File.Create(path + fileName);\n                f.Close();\n            }\n\n            _loadedSettings.AddRange(\n                ParseCamelotSettings(folderName + \"/\" + fileName, false, go).GetComponents<CamelotSetting>());\n        }\n\n        public static List<CamelotSetting> GetSettings()\n        {\n            return _loadedSettings;\n        }\n\n        #region Static Parser Functions\n\n        public static void SaveTriggerZoneToFile(string settingName, Transform zoneTransfrom, Transform camelotPosition)\n        {\n            var title = JsonHelpers.PairToJson(\"Title\", settingName);\n            var zone = JsonHelpers.PairToJson(\"Zone\", zoneTransfrom.ToJson());\n            var camel = JsonHelpers.PairToJson(\"Cam\", camelotPosition.ToJson());\n\n            AppendToFile(\"TriggerZonePositions.txt\", JsonHelpers.ListToJson(new List<string> {title, zone, camel}));\n\n        }\n\n        public static GameObject LoadTriggerZonesFromFile(string settingName)\n        {\n            var file = new StreamReader(CamelotSettingFilePath + \"TriggerZonePositions.txt\");\n            string line;\n            while ((line = file.ReadLine()) != null)\n            {\n                JSONNode node = JSONNode.Parse(line);\n                if (node[\"Title\"] + \"\" == settingName)\n                {\n                    var triggerZoneGo = new GameObject(\"Trigger Zone: \" + settingName, new[] {typeof (BoxCollider)});\n                    triggerZoneGo.GetComponent<BoxCollider>().isTrigger = true;\n                    var camPos = new GameObject(\"Camelot Position\");\n                    camPos.transform.SetParent(triggerZoneGo.transform, false);\n\n                    JsonHelpers.JsonToTransform(triggerZoneGo.transform, node[\"Zone\"] + \"\");\n                    JsonHelpers.JsonToTransform(camPos.transform, node[\"Cam\"] + \"\");\n                    file.Close();\n                    return triggerZoneGo;\n                }\n            }\n            file.Close();\n            return null;\n        }\n\n        public static void ClearFile(string fileName)\n        {\n            var file = File.CreateText(CamelotSettingFilePath + fileName);\n            file.Write(\"\");\n            file.Close();\n        }\n\n        public static void SaveSettingToFile(CamelotSetting setting, string fileName = \"\")\n        {\n            if (setting == null)\n            {\n                Debug.LogError(\"Current setting is set to null\");\n                return;\n            }\n            if (!OverwriteSavedSetting(setting, fileName == \"\" ? \"Standard.txt\" : fileName))\n            {\n                var result = setting.ToJson();\n                Debug.Log(result);\n\n                AppendToFile(fileName, result);\n            }\n        }\n\n        public static bool LoadSettingInto(CamelotSetting target, string savedSettingTitle)\n        {\n            var file = new StreamReader(StandardFullPath);\n            string line;\n            while ((line = file.ReadLine()) != null)\n            {\n                JSONNode node = JSONNode.Parse(line);\n                if (node[\"Title\"] + \"\" == savedSettingTitle)\n                {\n                    JsonToCamelotSetting(target, line);\n                    file.Close();\n                    return true;\n                }\n            }\n            file.Close();\n            Debug.Log(\"Couldn't find the camelot setting we were looking for\");\n            return false;\n        }\n\n        public static bool OverwriteSavedSetting(CamelotSetting setting, string fileName)\n        {\n            var file = new StreamReader(CamelotSettingFilePath + fileName);\n            StringBuilder sb = new StringBuilder();\n            string line;\n            var result = false;\n            while ((line = file.ReadLine()) != null)\n            {\n                JSONNode node = JSONNode.Parse(line);\n                if (node[\"Title\"] + \"\" == setting.Title)\n                {\n                    sb.AppendLine(setting.ToJson());\n                    result = true;\n                }\n                else\n                {\n                    sb.AppendLine(line);\n                }\n            }\n            file.Close();\n            OverwriteFile(fileName, sb.ToString());\n            return result;\n        }\n\n        public static List<string> GetSettingTitles()\n        {\n            var file = new StreamReader(StandardFullPath);\n\n            var result = new List<string>();\n\n            string line;\n            while ((line = file.ReadLine()) != null)\n            {\n                JSONNode node = JSONNode.Parse(line);\n                result.Add(node[\"Title\"]);\n            }\n            file.Close();\n            return result;\n        }\n\n        public static bool IsSaved(string title)\n        {\n            return GetSettingTitles().Any(s => s == title);\n        }\n\n        public static bool IsLoaded(string title)\n        {\n            return _loadedSettings.Any(l => l.Title == title);\n        }\n\n        public static string LoadCamelotSetting(string title)\n        {\n            var file = new StreamReader(StandardFullPath);\n\n            string line;\n            while ((line = file.ReadLine()) != null)\n            {\n                JSONNode node = JSONNode.Parse(line);\n                if (title == node[\"Title\"])\n                {\n                    file.Close();\n                    return line;\n                }\n            }\n            file.Close();\n            return \"\";\n        }\n\n        public static GameObject ParseCamelotSettings(string fileName, bool willClearFile = true,\n            GameObject addTo = null)\n        {\n            if (addTo == null)\n                addTo = new GameObject();\n\n            var file = new StreamReader(CamelotSettingFilePath + fileName);\n\n            string line;\n            while ((line = file.ReadLine()) != null)\n            {\n                var setting = addTo.AddComponent<CamelotSetting>();\n                JsonToCamelotSetting(setting, line);\n            }\n\n            file.Close();\n            var f = File.CreateText(CamelotSettingFilePath + fileName);\n            if (willClearFile)\n                f.Write(\"\");\n            f.Close();\n            return addTo;\n        }\n\n        private static void JsonToCamelotSetting(CamelotSetting setting, string json)\n        {\n            JSONNode node = JSONNode.Parse(json);\n\n            var type = setting.GetType();\n            var fields = type.GetFields();\n            foreach (var field in fields)\n            {\n                var val = node[field.Name];\n                if (field.FieldType == typeof (bool))\n                    field.SetValue(setting, val.AsBool);\n                else if (field.FieldType == typeof (float))\n                    field.SetValue(setting, val.AsFloat);\n                else if (field.FieldType == typeof (Transform))\n                {\n                    if (val.ToString() == \"\")\n                        continue;\n                    var tmpGo = new GameObject(field.Name);\n                    JsonHelpers.JsonToTransform(tmpGo.transform, val.ToString());\n                    field.SetValue(setting, tmpGo.transform);\n                    tmpGo.transform.SetParent(setting.transform, true);\n                }\n                else if (field.FieldType == typeof (string))\n                    field.SetValue(setting, val + \"\");\n                else if (field.FieldType == typeof (int))\n                {\n                    field.SetValue(setting, val.AsInt);\n                }\n                else if (field.FieldType == typeof (Vector3))\n                {\n                    field.SetValue(setting, JsonHelpers.JsonToVector(val+\"\"));\n                }\n            }\n        }\n\n\n        public static void AppendToFile(string name, string s)\n        {\n            var path = CamelotSettingFilePath + name;\n            if (name == \"\")\n                path = StandardFullPath;\n            var f = File.AppendText(path);\n            f.WriteLine(s);\n            f.Close();\n        }\n\n        public static void OverwriteFile(string fileName, string s)\n        {\n            var f = File.CreateText(CamelotSettingFilePath + fileName);\n            f.Write(s);\n            f.Close();\n        }\n\n        #endregion\n\n    }\n#endif\n}", "line": "23", "column": "10", "filename": "/Users/Morten/Documents/Unity/Feels5.1/Assets/Scripts/Camera System/CamelotSettingParser.cs"}
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 39, in run
    response = pool.urlopen('POST', self.url, body=self.data, timeout=self.timeout).data
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 617, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/Morten/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50301): Max retries exceeded with url: /addtoproject (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
```

**Comment by snebjornen** [comment]
I found a backup of 1.70 which is working perfectly. I don't know if this can give you any clues as to what is wrong.

**Comment by bksshetty** [comment]
Hi i am getting below error, I am using appium tool to run test with continuous integration tool for ios app, While running below command i am getting error.

$py.test test1.py

============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /Users/distiller/testmac, inifile: 
collected 1 items 

test1.py F

=================================== FAILURES ===================================
____________________________ AppiumTests.testCases _____________________________

self = <test1.AppiumTests testMethod=testCases>

    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'iOS'
        desired_caps['platformVersion'] = '8.4'
        desired_caps['deviceName'] = 'iPad Air'
        desired_caps['app'] = abspath('/Users/distiller/testmac/AW16.ipa')
>       self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

test1.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py:36: in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:87: in __init__
    self.start_session(desired_capabilities, browser_profile)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:141: in start_session
    'desiredCapabilities': desired_capabilities,
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:199: in execute
    response = self.command_executor.execute(driver_command, params)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py:395: in execute
    return self._request(command_info[0], url, body=data)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py:463: in _request
    resp = opener.open(request, timeout=self._timeout)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py:431: in open
    response = self._open(req, data)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py:449: in _open
    '_open', req)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py:409: in _call_chain
    result = func(*args)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py:1227: in http_open
    return self.do_open(httplib.HTTPConnection, req)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <urllib2.HTTPHandler instance at 0x10f672b48>
http_class = <class httplib.HTTPConnection at 0x10f4ac4c8>
req = <selenium.webdriver.remote.remote_connection.Request instance at 0x10f65ef38>
http_conn_args = {}, host = '127.0.0.1:4723'
h = <httplib.HTTPConnection instance at 0x10f672f38>
err = error(61, 'Connection refused')

    def do_open(self, http_class, req, **http_conn_args):
        """Return an addinfourl object for the request, using http_class.
    
            http_class must implement the HTTPConnection API from httplib.
            The addinfourl return value is a file-like object.  It also
            has methods and attributes including:
                - info(): return a mimetools.Message object for the headers
                - geturl(): return the original request URL
                - code: HTTP status code
            """
        host = req.get_host()
        if not host:
            raise URLError('no host given')
    
        # will parse host:port
        h = http_class(host, timeout=req.timeout, **http_conn_args)
        h.set_debuglevel(self._debuglevel)
    
        headers = dict(req.unredirected_hdrs)
        headers.update(dict((k, v) for k, v in req.headers.items()
                            if k not in headers))
    
        # We want to make an HTTP/1.1 request, but the addinfourl
        # class isn't prepared to deal with a persistent connection.
        # It will try to read all remaining data from the socket,
        # which will block while the server waits for the next request.
        # So make sure the connection gets closed after the (only)
        # request.
        headers["Connection"] = "close"
        headers = dict(
            (name.title(), val) for name, val in headers.items())
    
        if req._tunnel_host:
            tunnel_headers = {}
            proxy_auth_hdr = "Proxy-Authorization"
            if proxy_auth_hdr in headers:
                tunnel_headers[proxy_auth_hdr] = headers[proxy_auth_hdr]
                # Proxy-Authorization should not be sent to origin
                # server.
                del headers[proxy_auth_hdr]
            h.set_tunnel(req._tunnel_host, headers=tunnel_headers)
    
        try:
            h.request(req.get_method(), req.get_selector(), req.data, headers)
        except socket.error, err: # XXX what error?
            h.close()
>           raise URLError(err)
E           URLError: <urlopen error [Errno 61] Connection refused>

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py:1197: URLError

=========================== 1 failed in 0.36 seconds =========================== py.test test1.py returned exit code 1

**Comment by SnowFlowers** [comment]
google says git update-index --chmod=+x <file>
